### ISSUE TITLE
挑戦シミュレートを押しても何も起こらず、開発コンソールを確認すると例外が投げられている。

### ISSUE THREAD

**Issue by gusmachine** [kaz-mighty/newincrementalgame-simulator#12]
環境:
OS: Debian GNU/Linux bookworm
ブラウザ: Google Chrome	111.0.5563.41 (Official Build) beta (64-bit) 

やったこと:
1. [添付ファイルのデータ](https://github.com/kaz-mighty/newincrementalgame-simulator/files/10833775/save1.txt)をシミュレータに食わせる。
2. 挑戦タブを開く
3. 挑戦1のマスをクリック

期待されること:
- 挑戦1の必要時間が計算され、マス目が対応した色に塗られる。

実際に起きたこと:
-マス目はオレンジ色のまま。開発コンソールを覗くとクリックの際に以下の例外が投げられている。
```
break_infinity.min.js:1 Uncaught Error: [DecimalError] Invalid argument: infinity
    at s.fromString (break_infinity.min.js:1:3124)
    at new s (break_infinity.min.js:1:1870)
    at D (nig_sim.js:1:22)
    at Nig.simulatechallenges (nig_sim.js:1777:23)
    at nig_sim.js:2246:81
```
当該箇所は以下。
https://github.com/kaz-mighty/newincrementalgame-simulator/blob/f59042c0740b9f5dd0dd7e433cde079aee688e4c/nig_sim.js#L1735

break_infinity のエラーを投げている箇所は以下。
https://github.com/Patashu/break_infinity.js/blob/b6ef58fbac632b43cb41ddf523fe8aea4d116f2b/src/decimal.ts#L194

ちょっと原因がわかりませんがここまでで報告させていただきます。

**Comment by gusmachine** [comment]
break_infinity.js の17時間前のリリースによるものな気がしてきました。以下の行の tolower のせいで parseFloat('Infinity') --> Infinity が parseFloat('infinity') --> NaN になっているように見えます。

https://github.com/Patashu/break_infinity.js/blob/b6ef58fbac632b43cb41ddf523fe8aea4d116f2b/src/decimal.ts#L177

17時間前の v.2.1.0 からこの tolower が存在し、その前の v.2.0.0 (2021年リリース) では存在しなかったので、そう疑っています。

**Comment by gusmachine** [comment]
break_infinity 側にも報告しました。
https://github.com/Patashu/break_infinity.js/issues/152

**Comment by kaz-mighty** [comment]
ひとまずこちら側で修正しておきました。

**Comment by kaz-mighty** [comment]
直ってませんでした。
文字列`new Decimal('Infinity')` ではなく定数 `new Decimal(Infinity)`にすると大小比較がうまくいかないらしい。

**Comment by kaz-mighty** [comment]
break_infinityのバージョンを指定して解決。
